### ISSUE TITLE
可以实现匹配关键词A但不匹配关键词B吗？

### ISSUE THREAD

**Issue by Nigel-NI** [mryee2023/ns-feed#9]
举个例子，想收一台斯巴达的闪购鸡，只想关注出鸡的帖子，但是很多人都想收，推送的帖子也都是收鸡相关的。所以我想问一下未来会支持匹配“斯巴达”但是不匹配“收”的这种关键词设置吗？

**Comment by mryee2023** [comment]
> 举个例子，想收一台斯巴达的闪购鸡，只想关注出鸡的帖子，但是很多人都想收，推送的帖子也都是收鸡相关的。所以我想问一下未来会支持匹配“斯巴达”但是不匹配“收”的这种关键词设置吗？

这个建议不错，会考虑加到下一个版本更新中，我需要想一想如何用简洁的语法来表达这一点，尽量不让你们输入正则表达式。

**Comment by mryee2023** [comment]
> 举个例子，想收一台斯巴达的闪购鸡，只想关注出鸡的帖子，但是很多人都想收，推送的帖子也都是收鸡相关的。所以我想问一下未来会支持匹配“斯巴达”但是不匹配“收”的这种关键词设置吗？

https://github.com/mryee2023/ns-feed/blob/dev/src/app/lib/ns_feed_test.go#L57

当前已简单支持逻辑运算，你可以尝试添加一下 :)

可参考README中的语法说明

https://github.com/mryee2023/ns-feed/blob/dev/README.md
